-- Run this once in Supabase SQL Editor
create table if not exists public.mood_responses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  mood text not null,
  mood_label text,
  intensity integer not null check (intensity between 1 and 10),
  message text,
  need text,
  source text default 'mood-check-web'
);

alter table public.mood_responses enable row level security;

-- Anyone with the website may submit a response.
-- The public browser key is NOT allowed to read responses.
drop policy if exists "public can submit mood" on public.mood_responses;
create policy "public can submit mood"
on public.mood_responses
for insert
to anon
with check (true);

-- No SELECT policy for anon = responses stay unreadable from the public site.
-- View them privately in Supabase Table Editor while logged into your Supabase account.
